default:
    # Blueprint API
    'GET /:extension/:name': 'BlueprintController#find_all'
    'GET /:extension/:name/:id': 'BlueprintController#find'
    'PUT /:extension/:name/:id': 'BlueprintController#update'
    'POST /:extension/:name': 'BlueprintController#create'
    'DELETE /:extension/:name/:id': 'BlueprintController#delete'
